/**
 * This code was generated by Builder.io.
 */
import React, { useEffect, useState } from "react";
import OrderTabs from "./OrderTabs";
import ProfileSidebar from "./ProfileSidebar";
import styles from "./Profile.module.css";
import Header from "./Header";
import Footer from "./Footer";
import { useCheckUserLoggedUtil, useIsAdminUtil } from "../utilities";
import { useNavigate } from "react-router-dom";
import { useCustomerBackend, useUpdateCustomerInfoBackend, } from "../../backend/customer.backend";
import { toast } from "sonner";

const Profile = () => {
  const { isAdmin } = useIsAdminUtil();
  const { logged } = useCheckUserLoggedUtil();
  const nav = useNavigate();
  const { response, loading: loadingUpdate, error: errorUpdate, updateInfo } = useUpdateCustomerInfoBackend()
  const [info, setInfo] = useState([]);
  const { customer, loading, error } = useCustomerBackend()

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      if (isAdmin) {
        nav('/admin');
      } else if (!logged) {
        nav('/login');
      }
    }, 1000);

    if (!loading && !error && customer) {
      console.log(customer);
      setInfo(customer);
    }

    return () => clearTimeout(timeoutId);
  }, [isAdmin, logged, nav, loading, error, customer]);



  const handleUpdateUser = async () => {
    const x = {
      ...customer,
      name: 'Doe John',
      email: 'johndoe@email.com',
       address: 'USA', 
       contact_no: '33222111'
    }
    console.log(x);

    await updateInfo(x);
    toast.success(response)
  }




  return (
    <div className={styles.profileContainer}>
      <Header />
      <main className={styles.mainContent}>
        <OrderTabs />
        <ProfileSidebar />
        <Footer />
      </main>
    </div>
  );
};

export default Profile;
