/**
 * This code was generated by Builder.io.
 */
import React, { useEffect } from "react";
import OrderTabs from "./OrderTabs";
import ProfileSidebar from "./ProfileSidebar";
import styles from "./Profile.module.css";
import Header from "./Header";
import Footer from "./Footer";
import { useIsAdminUtil } from "../utilities";
import { useNavigate } from "react-router-dom";

const Profile = () => {
  const { isAdmin } = useIsAdminUtil();
  const nav = useNavigate();
  useEffect(() => {
    if (isAdmin) {
      nav('/admin')
    }
  },[isAdmin,nav])
  return (
    <div className={styles.profileContainer}>
      <Header />
      <main className={styles.mainContent}>
        <OrderTabs />
        <ProfileSidebar />
        <Footer />
      </main>
    </div>
  );
};

export default Profile;
